### ISSUE TITLE
Remove icons from translations

### ISSUE THREAD

**Issue by thorewi** [68publishers/cookie-consent#13]
Hi,

we have different type of clients and some of them consider the icons (cookie and loud-speaker) childish, some of them suggest to use other icons and so on. That's why it would be imho better to remove the icons completely. I can send pull request if you agree.

**Comment by jelen07** [comment]
Hi Tomáš, yeah, I completely agree. The emojis are relics from some presentations and since we haven't effort to manage default translations yet, they're still there. PR will be welcomed.
