### ISSUE TITLE
Any idea how to add something like on the picture

### ISSUE THREAD

**Issue by thorewi** [68publishers/cookie-consent#15]
Hello,

any idea how to add a sentence "Souhlas můžete odmítnout zde" like on the picture?

<img width="773" alt="Screenshot 2021-12-23 at 11 32 16" src="https://user-images.githubusercontent.com/605858/147227821-c21127c9-71d5-475a-bae9-a0617331df0c.png">

I know the original plugin doesn't support anything like this (because it's too specific), but normally I would add it through javascript as mentioned here:

https://github.com/orestbida/cookieconsent/issues/79#issuecomment-997640595

But how to achieve that in this GTM wrapper? Thank you.

**Comment by tg666** [comment]
Hello,
You can achieve this, for example, with the following tag:

<img width="1190" alt="Snímek obrazovky 2021-12-23 v 14 03 21" src="https://user-images.githubusercontent.com/24430186/147244411-82da7eca-e866-4783-9160-cd59cc6a6fb0.png">

```javascript
<script>
  $('document').ready(function () {
    CookieConsentWrapper.on('init', function (wrapper) {
      $('#c-bns').append('<div>Souhlas můžete odmítnout <a id="cm-reject-button" class="cc-link">zde</a></div>');
    
      $('#cm-reject-button').on('click', function (e) {
        wrapper.unwrap().hide();
        wrapper.unwrap().accept([]);
        
        e.preventDefault();
      });
    });
  });
</script>
```

**Comment by thorewi** [comment]
Perfect, works like a charm! Thank you.
