### ISSUE TITLE
GTM integration does not work

### ISSUE THREAD

**Issue by Sikipiki** [68publishers/cookie-consent#22]
When I used the GTM template and deployed it via GTM, sometimes the Cookies consent window appears in Google Chrome browser (v96.0.4664.110). Firefox v95.0.2 and Edge v96.0.1054.62 do not display anything. But JS and CSS files are downloaded.
Tested on OS Win10 21H2 (build 19044.1415).

Snippet from FF:
![obrazek](https://user-images.githubusercontent.com/8134599/147686869-07736666-3bc8-4d9e-ad5a-474bb425f70a.png)

Snippet from Edge:
![obrazek](https://user-images.githubusercontent.com/8134599/147688122-5a3f3132-7f73-4674-8e00-2aaf00f0de1e.png)

I tried it on another PC Win10 21H2 (build 19044.1415): Cookie consent didn't appear in any browser.
Mobile Android 11 - browser Chrome - nothing.

**Comment by tg666** [comment]
Hello,
We have a deployed/submitted container for our app and everything works in all browsers. Also, no one reporting the same or similar problem as you. Can you provide more information?

- what version of the package are you using?
- is your template in GTM updated? (the last release doesn't have to work with the template from an old version of the package)
- is the option `Show the widget as soon as possible` enabled in your tag?
- have you placed somewhere on your page a trigger button for the settings modal? automatically by a [configuration](https://github.com/68publishers/cookie-consent#settings-modal-trigger) or manually? Is the settings modal displayed after a click?
- is some error message in a browser console?

or something else that could help me. Thanks.

**Comment by Sikipiki** [comment]
I used template v0.2.7.

Now, in GTM, I deleted the old tag and template. Imported a new template v0.3.0 and created a new tag (with default values). 

![obrazek](https://user-images.githubusercontent.com/8134599/147755394-a6f332b9-7006-472b-9f40-09f91a30abc3.png)


- Trigger button for the settings modal is placed manually.
- No errors in console

**Testing:**
my PC (W10) - Google Chrome -> Show cookie conset
my PC (W10) - other browsers (FF and Edge) -> nothing
mobile - Android - Chrome -> nothing
second PC at home (W10) -> nothing in all browsers (FF, Chrome and Edge)
PC at work (W10) -> nothing in all browsers (FF, Chrome and Edge)

**Result of commands CookieConsentWrapper and CookieConsentWrapper.unwrap(); see image**
![obrazek](https://user-images.githubusercontent.com/8134599/147756734-16b639f9-3836-4eb9-83d4-33be780e3cad.png)

**Comment by tg666** [comment]
@Sikipiki Hello,

We looked on your website that you sent to Vojta and I think I found the problem. Initialization of the original plugin is placed into an event `window.addEventListener('load', ... the original plugin initialization ...)` and your page is so small that it loaded before the event attached.
Of course, it's a bug so I fixed it in a beta version `0.3.1-beta.0`. Can you update the field `Package version` in the configuration of your tag and tell if everything works OK?

<img width="288" alt="Snímek obrazovky 2021-12-31 v 3 33 40" src="https://user-images.githubusercontent.com/24430186/147799708-bd147983-2d5f-4e59-b4a2-828a5de208a1.png">

Then I'll release it as a stable version. Thank you!

**Comment by Sikipiki** [comment]
Thank you. It works!

Dne 2021-12-31 03:34, tg666 napsal:

**Comment by tg666** [comment]
Perfect! I'm going to release the version `0.3.1`.
