### ISSUE TITLE
How to create a variable which returns if any storage was granted

### ISSUE THREAD

**Issue by thorewi** [68publishers/cookie-consent#24]
Hello,

how to create for example "ad_analytics_storage" variable, which returns if both ad_storage and analytics_storage was granted? Thank you very much.

**Comment by tg666** [comment]
Hello,
I don't know exactly what you want to achieve. Are you talking about GTM variable or javascript variable?
I tried something like this:

GTM variable (the variable contains a closure):
<img width="1176" alt="Snímek obrazovky 2022-01-02 v 4 08 07" src="https://user-images.githubusercontent.com/24430186/147864978-5d4275b8-1672-433e-a798-eac0357cd413.png">

Tag:
<img width="935" alt="Snímek obrazovky 2022-01-02 v 4 08 58" src="https://user-images.githubusercontent.com/24430186/147864986-59cdef8b-54bb-412f-bd23-b19a1071247f.png">

Using in the console (before consent and after "accept all"):
<img width="241" alt="Snímek obrazovky 2022-01-02 v 4 10 14" src="https://user-images.githubusercontent.com/24430186/147865009-dbd23cb6-9075-4aee-8b48-10ca7f798a64.png">

But I don't know your UC.

**Comment by thorewi** [comment]
That's exactly what I wanted. Thank you!
