### ISSUE TITLE
Accept necessary + modify 

### ISSUE THREAD

**Issue by AlkoKod** [68publishers/cookie-consent#28]
Hello, thank you for your hard work. I spent a weeks creating my own customizations on orestbidas cookie constent, but I never find out, how to make clearing of cookies working. 

I want to ask, if there is a posibility to use second button only for necessary cookies and add the third button/link to modify cookie preferences. Maybe I am just blind. but I didnt found this in the settings.

![image](https://user-images.githubusercontent.com/52713604/148240309-fd6b07d4-6bfd-4e15-bdf3-c4601c1ae33c.png)

Thank you very much!

**Comment by tg666** [comment]
Hello,

## Cookies clearing
The original plugin (orestbida) uses cookie tables for cookies auto-clear. Each storage (category) can define a cookie table with cookies that the storage uses. Then the plugin knows which cookies delete according to the user preferences.

However, our integration currently doesn't support cookie tables. We implemented custom auto-clear strategies, that flushes all defined cookies or all cookies except that ones you want to kept.

The [section about cookies](https://github.com/68publishers/cookie-consent#cookies-options) in the README contains description about auto-clearing.
Here is an issue with a discussion about it: https://github.com/68publishers/cookie-consent/issues/19

## The second button as "accept necessary"

`Consent modal options > Secondary button role > Accept necessary`

<img width="347" alt="Snímek obrazovky 2022-01-05 v 19 42 32" src="https://user-images.githubusercontent.com/24430186/148271228-05cee710-e162-4011-8efe-65d4d1f0aabd.png">


## Custom link that opens the settings in the consent modal
This can be done in two ways:

1) Rewrite a translation with the key `consent_modal_description` in a tag configuration (the section `Translation settings > Translations`):

<img width="631" alt="Snímek obrazovky 2022-01-05 v 19 38 29" src="https://user-images.githubusercontent.com/24430186/148270700-8073f117-63c8-406d-85ad-e1004d0005ea.png">

OR

2) Add the link in JavaScript manually:

```javascript
<script>
  CookieConsentWrapper.on('init', function () {
    var link = document.createElement('a');

    link.setAttribute('class', 'cc-link');
    link.innerText = 'Cookie settings';
    
    link.addEventListener('click', function (e) {
      CookieConsentWrapper.unwrap().showSettings(0);
      e.preventDefault();
    });
    
    document.getElementById('c-txt').appendChild(link);
  });
</script>
```
<img width="929" alt="Snímek obrazovky 2022-01-05 v 22 15 46" src="https://user-images.githubusercontent.com/24430186/148290582-276f79f5-e08f-419d-ab71-6cab57a88dd4.png">

**Comment by AlkoKod** [comment]
Thank you very much. The translation option is good enough!
