### ISSUE TITLE
Document language not working with cz-CZ

### ISSUE THREAD

**Issue by AlkoKod** [68publishers/cookie-consent#29]
Hello, I am trying to change the language by document html language: 

In Tag manager I have this: 

![image](https://user-images.githubusercontent.com/52713604/148244303-db4bfe80-6d9f-4b2e-bee5-a6a41dadd686.png)

In HTML: 

`<html lang="cs-CZ" class="show--consent">`
`<html lang="en-US" class="show--consent">`

but it doesn't change at all. What should I do?

**Comment by jelen07** [comment]
Hi Aleš! As mentioned in [README](https://github.com/68publishers/cookie-consent#:~:text=in%20the%20format-,ISO%20639%2D1,-and%20each%20locale), the language codes have to be **ISO 639-1**. If you're using different codes, use them as translation keys as well.

**Comment by tg666** [comment]
@AlkoKod Hello, I already released the version `v0.3.3` that "fixes" it.

Just update the package version and define your locales in a tag configuration:

<img width="401" alt="Snímek obrazovky 2022-01-05 v 19 11 08" src="https://user-images.githubusercontent.com/24430186/148267436-83264285-1a66-4b59-b537-4e38fde413be.png">

Default translations will be used.

**Comment by AlkoKod** [comment]
> @AlkoKod Hello, I already released the version `v0.3.3` that "fixes" it.
> 
> Just update the package version and define your locales in a tag configuration:
> 
> <img alt="Snímek obrazovky 2022-01-05 v 19 11 08" width="401" src="https://user-images.githubusercontent.com/24430186/148267436-83264285-1a66-4b59-b537-4e38fde413be.png">
> 
> Default translations will be used.

Thank you very very much! ♥️🌶️
