### ISSUE TITLE
Using default Tag Manager Consent API instead of custom triggers

### ISSUE THREAD

**Issue by AlkoKod** [68publishers/cookie-consent#30]
Hello, 

do you plan to use the Consent API instead of custom triggers? I tried something like this in the past:  [https://github.com/AlkoKod/websites/blob/main/Cookie%20li%C5%A1ta%20s%20GTM%20Consent%20mode](url)

But I never make the cookie auto clean working.

**Comment by tg666** [comment]
If I'm not mistaken, the native Consent API only supports a few services like GA and Ads, the rest must be handled by yourself (triggers).

But we are sending consent updates through `gtag` function:

https://github.com/68publishers/cookie-consent/blob/v0.3.4/src/ConsentManager.js#L63

The default consent initialization is inside the template:

https://github.com/68publishers/cookie-consent/blob/v0.3.4/gtm_template.tpl#L1353

**Comment by AlkoKod** [comment]
Okay, I propably misunderstood the setup of tags in Tag manager. Thanks for clarification. You did very nice job.
