### ISSUE TITLE
CSS problem with RTL

### ISSUE THREAD

**Issue by pinkasey** [68publishers/cookie-consent#42]
This is what the plugin looks like with `direction: rtl;` in the body:
![image](https://user-images.githubusercontent.com/1780369/193817139-6b5c17d3-4986-4098-888a-773102b82b0e.png)

For reference, here it is with `direction: ltr;`
![image](https://user-images.githubusercontent.com/1780369/193817270-4d6d135e-ca2c-4ad2-a887-0ffe9e6afa93.png)

**Comment by tg666** [comment]
Hi,
Unfortunately, default styles are not part of this integration, but are part of the [original plugin](https://github.com/orestbida/cookieconsent) by @orestbida.
You can try to create a pull request in the original plugin.

**Comment by pinkasey** [comment]
Thank you very much, @tg666 !
I've opened an issue in the original plugin, and I might open a PR later on.
So closing this one.

It's still good to have this closed-issue as documentation for other users.
