### ISSUE TITLE
Ability to set cookie domain

### ISSUE THREAD

**Issue by keesvandieren** [68publishers/cookie-consent#46]
The plugin `orestbida/cookieconsent` supports configuring a cookie domain.

However it seems to be not possible to set this using Tag Manger.

Is it possible to add the `cookie_domain` configuration option of https://github.com/orestbida/cookieconsent to the Tag Manager Cookie Options settings?

Usecase: we are using sub-domains, but we'd like to share the consent given between www.example.com, sub-domain.example.com and example.com.

So we'd like to set example.com as cookie domain.

**Comment by tg666** [comment]
Hi!
We have already implemented this feature in a beta version with other features.
I'll go through it tomorrow, finish the readme and release.

**Comment by keesvandieren** [comment]
Awesome 😎. Looking forward to the release.

**Comment by tg666** [comment]
Version `0.4.0` released.
More features were added. If there happens to be any problem with the update, please let me know here 🙂
