### ISSUE TITLE
Consent management not working correctly when analytics cookies enabled by default

### ISSUE THREAD

**Issue by RogierKuiper** [68publishers/cookie-consent#52]
It seems the consent manager is not correctly blocking analytics cookies when analyitcs cookies are set to be enabled by default and the user declines these cookies. 

The first party cookie for the consent manager is correctly set though, the settings panel also shows the correct settings but Tag manager still fires Google all analytics cookies. It seems the consent manager is not loading the right information at Consent initialisation.

![Screenshot 2023-04-20 at 12 55 07](https://user-images.githubusercontent.com/131358096/233345909-6f46a420-f35b-40eb-9797-972bc355c798.png)

**Comment by tg666** [comment]
Hi @RogierKuiper, thanks for the report!
It should be fixed in branch `main`, just update the GTM template.
