### ISSUE TITLE
Not sending pageview request on consent?

### ISSUE THREAD

**Issue by will-yellowpeach** [68publishers/cookie-consent#62]
We're using your GTM implementation which is great first of all.

When a visitor first lands on the site GA is blocked, but at the point of giving consent it doesn't seem to send a pageview request to GA for that initial view - meaning we always miss out on tracking that initial pageview. Is that as expected?

If that is as expected, is there any way to trigger that pageview request after consent?

**Comment by jelen07** [comment]
Hi @will-yellowpeach,

This depends on the implementation on the GTM side. Do you notice the described behavior e.g. on https://www.datart.cz?

**Comment by jelen07** [comment]
For time reasons I can't send you more detailed information, but the main idea of implementing these UCs is that if you don't have consent, you collect the data or any analytics on the client, but you don't send it. Once you have consent, you send all the data collected so far.

This could be handled similarly to the initial visit. You save it in your dataLayer and only send it when you have consent.

Some tools try to help with this, and their clients or tracking functions initialize in "I have"/"I don't have" consent mode. You can additionally call over them that the user has granted or denied consent and they will behave accordingly (collect data vs collect and send).

A similar approach is described for example in the SpeedCurve tool https://support.speedcurve.com/docs/cookie-consent-banners

There are many articles on the web that address this issue, e.g. https://www.cardinalpath.com/blog/consent-mode-delivering-analytics-while-respecting-consent

It's not so much a 68publishers/cookie-consent issue as it is an implementation of these tools along with consent mode.

I believe this will help.

**Comment by jelen07** [comment]
Example

<img width="978" alt="Snímek obrazovky 2023-10-24 v 19 39 31" src="https://github.com/68publishers/cookie-consent/assets/2346295/9c1a3741-a43e-45a5-ae59-76d3aac19301">

**Comment by will-yellowpeach** [comment]
@jelen07 makes sense, thanks for the pointers
