### ISSUE TITLE
Reject all cookies

### ISSUE THREAD

**Issue by juansebas0712** [68publishers/cookie-consent#65]
Hi guys, thanks for this amazing integration with GTM. Do you have any plans to add a button with the option to reject all cookies? According to the EU law, this is required.

Thank you very much again.

**Comment by jelen07** [comment]
Hi @juansebas0712, do you have any documentation, guidelines that state this?
Isn't this just a misinterpretation of "Reject all optional"?

In the case of "Reject all cookies" you lose the ability to save the user's choice to reject all cookies, which will cause the cookie bar to reappear 🤦

**Comment by juansebas0712** [comment]
I think you are right, I could use the "Accept necessary" option and change it's text to reject all. Thanks
