### ISSUE TITLE
Visual appearance of the bar

### ISSUE THREAD

**Issue by jiigtaCz** [68publishers/cookie-consent#69]
Hello, is there any way to define the final form of the bar? The documentation describes that it should be possible using Stylesheets. However, I admit that I have not been able to make any modifications using CSS. For example, would it be possible to somehow link the visual form of the bar to what one defines on the OrestBida playground:https://playground.cookieconsent.orestbida.com/?

Thanks a lot for the answer

**Comment by jelen07** [comment]
> However, I admit that I have not been able to make any modifications using CSS.

Is there a reason for that?

**Comment by jiigtaCz** [comment]
> > However, I admit that I have not been able to make any modifications using CSS.
> 
> Is there a reason for that?

For example, if I wanted to slightly change the color of the action buttons, the size of the banner, etc.

**Comment by jelen07** [comment]
I'm not asking about specific graphic modifications, I'm asking **why you can't change** the CSS.

However, on the "playground" page you have to download the generated configuration according to your preferences + there are CSS styles for each theme.

Please note that playground is for version 3+, while `68publishers/cookie-consent` supports version 2 for now.

**Comment by tg666** [comment]
I see no problem.

<img width="885" alt="Screenshot 2024-02-27 at 17 12 36" src="https://github.com/68publishers/cookie-consent/assets/24430186/23f3e77b-8cc1-4070-96ca-988520758872">

<img width="395" alt="Screenshot 2024-02-27 at 17 11 48" src="https://github.com/68publishers/cookie-consent/assets/24430186/3fa0e898-40d4-4cb9-8cf1-373bd489d4af">

**Comment by jiigtaCz** [comment]
Ok, sorry guys, it was my fault - I'm a beginner at this. Could I please ask about the parameter implementation for CM v2?

**Comment by tg666** [comment]
> Could I please ask about the parameter implementation for CM v2?

GCM v2 has been already implemented in the version [v0.5.0](https://github.com/68publishers/cookie-consent/releases/tag/v0.5.0)
https://github.com/68publishers/cookie-consent/issues/63#issuecomment-1965817702

**Comment by jiigtaCz** [comment]
> > Could I please ask about the parameter implementation for CM v2?
> 
> GCM v2 has been already implemented in the version [v0.5.0](https://github.com/68publishers/cookie-consent/releases/tag/v0.5.0) [#63 (comment)](https://github.com/68publishers/cookie-consent/issues/63#issuecomment-1965817702)

Great, thank you so much!
