### ISSUE TITLE
Cookies Banner checking for "previous version of saved cookies"

### ISSUE THREAD

**Issue by horde45** [68publishers/cookie-consent#75]
Hi,

your template works like a charm! I can not thank you enough! However I came across this issue:

Users visiting a website where they gave consent to previous cookies solution before March 2024 are not presented automatically with your cookies banner. I guess that is based on the longevity / lifespan of the cookies consents given to the previous version of the cookies bar. However this leads to a situation that new remarketing storages "ad_user_data" and "ad_personalization" are not gathered thus actions of these "previous" visitors can not be tracked unless they either clear manually the cookies in their browser or those consents from the previous banner expire. This is what ChatGPT called it.. is there some way how you could get around this by further updates of your ingenious template?

Dynamic Consent Management:

Implement a dynamic consent management system that checks the user's stored consent preferences when they revisit the website.
Display an updated cookie consent banner or pop-up that reflects any changes to cookie categories or purposes since the user's last visit.
Provide clear options for users to review and update their consent preferences based on the new cookie settings.

**Comment by tg666** [comment]
Hi,
There is a "Revision" field in the template for this purpose. If you increase the revision number, all users will see the cookie bar again.
https://github.com/68publishers/cookie-consent?tab=readme-ov-file#how-to-manage-revisions

**Comment by horde45** [comment]
Thanks for the tip - but somehow it doesnt work for me. I changed the revision number from 0 to 1, published the GTM container and browser did not display your cookie banner again. Is there something else that needs to be changed?

**Comment by horde45** [comment]
now.. Im not a programmer. but I asked Chat GTP if I can somehow impose on the visitors the fact - hey, there is a new cookies bar that you have to agree with..  it came up with the script below.. Is it something that can be incorporated into your template that whoever gave the consent before I implemented your solution - would have to agree with your new cookie banner?

// Check if the consent cookie exists and if it has expired
function checkCookieConsent() {
  var consentCookie = getCookie("cookie_consent");
  if (consentCookie !== "") {
    var expirationDate = new Date("2022-01-01"); // Example expiration date
    var currentDate = new Date();
    if (currentDate > expirationDate) {
      // Consent has expired, show the new cookie consent banner
      showNewCookieBanner();
    }
  } else {
    // Cookie consent doesn't exist, show the new cookie consent banner
    showNewCookieBanner();
  }
}

// Function to get the value of a cookie by name
function getCookie(name) {
  var cookies = document.cookie.split(';');
  for (var i = 0; i < cookies.length; i++) {
    var cookie = cookies[i].trim();
    if (cookie.startsWith(name + '=')) {
      return cookie.substring(name.length + 1);
    }
  }
  return "";
}

// Function to display the new cookie consent banner
function showNewCookieBanner() {
  // Your code to display the new cookie consent banner goes here
  console.log("Show new cookie consent banner");
}

// Call the checkCookieConsent function when the page loads
window.onload = function() {
  checkCookieConsent();
};

**Comment by tg666** [comment]
> Thanks for the tip - but somehow it doesnt work for me. I changed the revision number from 0 to 1, published the GTM container and browser did not display your cookie banner again. Is there something else that needs to be changed?

Didn't you already accept the bar in Preview mode in the GTM?
The revisions really work, I just tried it.

You can check your cookie in the browser to see what revision it has. In Chrome DEV Console > Application > Cookies > [your domain] > `cc-settings` cookie (by default).
The cookie value should show the revision that was consented to.

<img width="657" alt="Screenshot 2024-03-19 at 9 04 02" src="https://github.com/68publishers/cookie-consent/assets/24430186/908d059a-b347-4095-acf1-f13c08196844">

**Comment by jelen07** [comment]
Hi, @horde45 

> Users visiting a website where they gave consent to previous cookies solution before March 2024 are not presented automatically with your cookies banner. I guess that is based on the longevity / lifespan of the cookies consents given to the previous version of the cookies bar. However this leads to a situation that new remarketing storages "ad_user_data" and "ad_personalization" are not gathered thus actions of these "previous" visitors can not be tracked unless they either clear manually the cookies in their browser or those consents from the previous banner expire.

That's something you should answer on your side. There are different views on this from a legal perspective. It also depends what cookies/providers you use, as well as the type of your project (e-commerce, non-profit, etc.).
One such view, for example, is that if you don't have user consent, you shouldn't pretend like you do. If you've made some major changes, such as adding those two new categories you want to "measure", you should prompt the user for a new approval. This is what the revision parameter is for, as @tg666 wrote.
Theoretically, you should also use it if you change the text (in a deeper sense - e.g. new site/app owner) or cookie terms and so on.

However, for some edge cases, the bar allows you to "sync" categories with others. For example, you can set `ad_user_data` and `ad_personalization` to sync to agree with `ad_storage`. The moment you have user consent to `ad_storage`, you can measure these two as well (reps. will send the correct events to GTM).

**Comment by horde45** [comment]
Thanks for the info above. but as I pointed out changing the revision number does not work for me - the cookies banner simply does not reappear.

**Comment by horde45** [comment]
> > Thanks for the tip - but somehow it doesnt work for me. I changed the revision number from 0 to 1, published the GTM container and browser did not display your cookie banner again. Is there something else that needs to be changed?
> 
> Didn't you already accept the bar in Preview mode in the GTM? The revisions really work, I just tried it.
> 
> You can check your cookie in the browser to see what revision it has. In Chrome DEV Console > Application > Cookies > [your domain] > `cc-settings` cookie (by default). The cookie value should show the revision that was consented to.
> 
> <img alt="Screenshot 2024-03-19 at 9 04 02" width="657" src="https://private-user-images.githubusercontent.com/24430186/313970568-908d059a-b347-4095-acf1-f13c08196844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDA1NjMsIm5iZiI6MTcxMDg0MDI2MywicGF0aCI6Ii8yNDQzMDE4Ni8zMTM5NzA1NjgtOTA4ZDA1OWEtYjM0Ny00MDk1LWFjZjEtZjEzYzA4MTk2ODQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA5MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMWYxZGM5MGU5ODFkYWE0NDlhM2QzN2VlMTcxYzlkZmE3Y2U4ODdiNzJiNWRkNzU1ZDdkYzZjYjQwNjQyMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8hcQXV9C1bBCB0-s0pGSWOTYENwCiqUGZCQGpARQoFQ">

It works in GTM preview mode perfectly well - once I publish it the bar does not reappear on the web

**Comment by jelen07** [comment]
I'm afraid we're not able to help you without a link to the site or a sample implementation.

**Comment by tg666** [comment]
> It works in GTM preview mode perfectly well - once I publish it the bar does not reappear on the web

That's what I was talking about. If you've already given consent in preview mode, it won't show up for you on the site once it's published. Preview mode opens your site normally, so once you give a consent, a new consent with the current revision is stored in the cookie.

**Comment by horde45** [comment]
> > It works in GTM preview mode perfectly well - once I publish it the bar does not reappear on the web
> 
> That's what I was talking about. If you've already given consent in preview mode, it won't show up for you on the site once it's published. Preview mode opens your site normally, so once you give a consent, a new consent with the current revision is stored in the cookie.

maybe im really dumb.. but in my GTM preview mode I put in revision field number 3 - the cookie bar reappeared. I then changed the revision number to 4 (did not try it again in GTM preview mode) and published it. And the bar did not reappear.

**Comment by jelen07** [comment]
Can you upload the steps so we can figure out what's wrong? Alternatively, share the GTM container to vojtech.lacina@68publishers.io so we can check it.

**Comment by horde45** [comment]
mě fakt nebaví každou chvíli zjištovat, proč mi nefunguje zase heslo do Githubu . .navíc reagovat na 1 z cca 8 postů po půl roce opravdu není dobrá vizitka.. podle mě za tím issue stojí nesoulad mezi číslem revize + zadání doby platnosti ve dnech u jednotlivých consentů.. zkrátka se nějak "přebíjí"
______________________________________________________________
> Od: "Vojtěch Lacina" ***@***.***>
> Komu: "68publishers/cookie-consent" ***@***.***>
> Datum: 02.10.2024 14:42
> Předmět: Re: [68publishers/cookie-consent] Cookies Banner checking for "previous version of saved cookies" (Issue #75)
>
 
Can you upload the steps so we can figure out what's wrong? Alternatively, share the GTM container to ***@***.*** ***@***.***> so we can check it.

**Comment by jelen07** [comment]
@horde45 I'd like to clarify a few things first. 

No one is forcing you to use our software. You are using software that costs over 50,000 USD for free, without any financial contribution. That does not even count the associated apps or the original plugin.

Just to remind you, we share the source code voluntarily, and we are under no obligation to answer to anyone or to deal with anyone, as we are solving this on our own time.

We are happy whenever our software can help [any users with their projects](https://github.com/68publishers/cookie-consent/stargazers) and save them considerable resources.

What we definitely don't want are random individuals without humility and self-reflection who can't even log into GH. So I can say with a calm heart that this software is not for you.

Everyone else is welcome.

**Comment by horde45** [comment]
to jsi mi to ale "natřel".. hlavně, že tvé ubližené ego neutrpělo... ono totiž, když je něco "zadarmo", tak každý to musí jenom chválit a nemůže říci jediného slova - jako že třeba když se na ten projekt vynaložilo tolik energie a času, tak by se to možná mohlo odrazit i v diskusi, kterou někdo kontroluje - když u stojí o podněty uživatelů.
 
 
______________________________________________________________
> Od: "Vojtěch Lacina" ***@***.***>
> Komu: "68publishers/cookie-consent" ***@***.***>
> Datum: 02.10.2024 14:42
> Předmět: Re: [68publishers/cookie-consent] Cookies Banner checking for "previous version of saved cookies" (Issue #75)
>
 
Can you upload the steps so we can figure out what's wrong? Alternatively, share the GTM container to ***@***.*** ***@***.***> so we can check it.
