### ISSUE TITLE
Google finally clarifies status of "consent v2" marketing cookies

### ISSUE THREAD

**Issue by horde45** [68publishers/cookie-consent#76]
Why do we automatically map "ad_storage" to "ad_user_data" while a manual upgrade to consent mode (V2) is required for "ad_personalization"?

https://support.google.com/tagmanager/answer/14754100?utm_source=awfe&utm_medium=email&utm_campaign=20310342

I translate this as follows:

a) previous "ad_storage" = "ad_user_data" = MARKETING cookies (as generally called in the banner)
b) content with a single lever / button MARKETING cookies does not constitute legal consent with both "ad_user_data" and "ad_personalization"
c) per EDPB (European Data Protection Board) the consent with individual cookies should be granular (one at a time, not pushed to choose "all - or nothing") .. the "ad_personalization" should not be bound with some general "marketing consent".

thus.. I can see that the current layout for version 5.00 of the banner could reflect this public declaration by Google and instead of:

marketing cookies (ad_storage)
- ad_user_data
- ad_personalization

just to get rid of the nested sub-consents and at the first-level menu offer choices:

marketing cookies (ad_storage + ad_user_data)
personalization cookies (ad_personalization)

perhaps not much of a difference. but from the UX point of view it would make the banner clearer and also more easily displayed on 20" inches screens that tend to request some of the scrolling while displaying certain banner layouts.

just a thought how to improve the banner. Im pretty happy with the existing concept.

**Comment by jelen07** [comment]
Due https://github.com/68publishers/cookie-consent/stargazers
