### ISSUE TITLE
#cookie-settings link not working on a gatsby site

### ISSUE THREAD

**Issue by socmov** [68publishers/cookie-consent#81]
Thanks for this time-saving module. 

I have set up the cookie consent using google tag manager. I have an identical set up on two sites: one build with Gatsby and one built with NextJS. The NextJS site works fine but the gatsby site has an issue triggering the Cookie Settings modal. The initial prompt works fine but when I try to view the cookie settings the link does not work. 

The site is https://uxdx.com. You can see on first load that the prompt works correctly. However clicking on the Cookie Settings link in the footer does nothing. The url changes to include the #cookie-settings but the modal does not appear.

**Comment by jelen07** [comment]
Hi @socmov,

was it resolved?
