### ISSUE TITLE
CC'68 after iOS 18.0.1 update

### ISSUE THREAD

**Issue by tomasz-wnuk** [68publishers/cookie-consent#91]
After updating iOS to iOS 18.0.1 I have signals (I personally do not have an iPhone) that the CM'68 banner is not displayed. Can I ask the creators of CM'68 to check and update?

**Comment by jelen07** [comment]
Hi Tomasz, can you be more specific, maybe add some context? For example, a link where the bar is not displayed.

**Comment by tomasz-wnuk** [comment]
One me mistake, update iOS 18.1.1 checked on Safari iPhone 14 on the website https://zaczarowanasypialnia.pl/

**Comment by tomasz-wnuk** [comment]
Have you checked it on Safari? We just checked in the office on 3xIPhone - Safari browser (iPhone13 - IOS 18.1.1 , iPhone11Pros - IOS 17.6 , iPhone14 - IOS 18.1.1), the banner is not visible on any of them

**Comment by jelen07** [comment]
The screen from previous post is from Safari - iPhone 15 Pro.
Now tested on
1. iPhone SE, iOS 15.8.3.
2. iPhone 16 Pro Max, iOS 18.0.1

And it works everywhere.

Is it possible that you have already accept/denied the bar and that is why it is not showing? You can verify this by incrementing the [revision number in GTM](https://github.com/68publishers/cookie-consent?tab=readme-ov-file#how-to-manage-revisions).

You should also [setup a modal settings trigger](https://github.com/68publishers/cookie-consent?tab=readme-ov-file#settings-modal-trigger).

**Comment by tomasz-wnuk** [comment]
Everything is clear now, sorry for the confusion. The reports were about incognito mode, in normal mode everything works fine.

**Comment by jelen07** [comment]
Did you mean "Private" session on Safari?

**Comment by tomasz-wnuk** [comment]
as I mentioned I don't use iPhone, but yes, it's about 'New private window'

**Comment by jelen07** [comment]
This is the feature of Private Browsing, not a bug of cookie consent. See https://moonlock.com/private-browsing-on-iphone
