### ISSUE TITLE
Consentbanner now showing text in Edge

### ISSUE THREAD

**Issue by JeaNette-hub-alt** [68publishers/cookie-consent#92]
My consentbanner is working fine in Chrome, but is lacking Text and function in Edge browser. Does anyone got tips? Website www.alvoen.no

**Comment by JeaNette-hub-alt** [comment]
![MissingText](https://github.com/user-attachments/assets/5ce5faf2-40d0-4dd7-bea2-13e2d684ee94)
![withtext](https://github.com/user-attachments/assets/7552cdd8-9c3c-4dc6-a2da-bfac7eac1cd3)

**Comment by jelen07** [comment]
You have some errors in console. You should fix them as first. That leads to your missing translations. It's not just Edge issue.

<img width="2167" alt="Snímek obrazovky 2024-11-29 v 14 52 20" src="https://github.com/user-attachments/assets/91d2db5e-0002-4353-934a-18d26d0d161f">

Try to load the translation from the same subdomain - coz of `Referrer Policy: strict-origin-when-cross-origin` ie. https://www.alvoen.no/Files/Images/Alvoen/Gallerier/no.json

**Comment by JeaNette-hub-alt** [comment]
Thank you. This was very helpful :) It is working now.
